/*
 * File: app/view/ui/MyViewport.js
 * Date: Sat Sep 10 2011 12:23:48 GMT+0200 (W. Europe Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.personen.Personen', {

    alias : 'widget.personenMitarbeiter',
    extend: 'Ext.container.Container',
    
    width: 700,
    
    initComponent: function() {    	
    	var me = this;
        
    	/* TODO: hier brauche ich die Daten für das Formular */
    	Ext.Ajax.request({
    	    url: 'ajax_demo/sample.json',
    	    success: function(response, opts) {
    	        var obj = Ext.decode(response.responseText);
    	        console.dir(obj);
    	    },
    	    failure: function(response, opts) {
    	        console.log('server-side failure with status code ' + response.status);
    	    }
    	});    	
    	
    	
    	
        var storeVertragsdaten = Ext.create('Ext.data.Store', {
            autoLoad: true,
            autoSync: true,
            model: 'AM.model.HiWiVertrag',  
        });               
        
        me.items = [
            {
                xtype: 'liveSearchGridPanel',
                itemId: 'personenGrid',
                title: 'Eingestellte HiWis',
                margin: '10 0 10 0',
                store: storeVertragsdaten,
                columns: [
                       
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'hiwi',
                        text: 'Name',
                        flex: 1,
                    },
                    {
                        xtype: 'datecolumn',
                        dataIndex: 'begin',
                        text: 'Vertragsbeginn',
                    	format: 'd.m.y',
                    },
                    {
                        xtype: 'datecolumn',
                        dataIndex: 'end',
                        text: 'Vertragsende',
                        format: 'd.m.y',
                    },                       
                    {
                        xtype: 'numbercolumn',
                        dataIndex: 'remainingHours',
                        text: 'Offene Stunden'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'remainingTasks',
                        text: 'Offene Aufgaben'
                    }
                ],
                viewConfig: {

                }
            },
        ];
        me.callParent(arguments);
    }
});