/*
 * File: app/view/ui/MyViewport.js
 * Date: Sat Sep 10 2011 12:23:48 GMT+0200 (W. Europe Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.dashboard.Mitarbeiter', {

    alias : 'widget.dashboardMitarbeiter',
    extend: 'Ext.container.Container',
    
    width: 700,
    
    initComponent: function() {    	
    	var me = this;
        
    	/* TODO: hier brauche ich die Daten für das Formular */
    	Ext.Ajax.request({
    	    url: 'ajax_demo/sample.json',
    	    success: function(response, opts) {
    	        var obj = Ext.decode(response.responseText);
    	        console.dir(obj);
    	    },
    	    failure: function(response, opts) {
    	        console.log('server-side failure with status code ' + response.status);
    	    }
    	});    	
    	
    	
    	
        var storeVertragsdaten = Ext.create('Ext.data.Store', {
            autoLoad: true,
            autoSync: true,
            model: 'AM.model.HiWiVertrag',  
        });      
        var storeAufgaben = Ext.create('Ext.data.Store', {
            autoLoad: true,
            autoSync: true,
            model: 'AM.model.HiWiAufgabe',  
        });              
        
        me.items = [
            {
                xtype: 'gridpanel',
                itemId: 'vertragsendeGrid',
                title: 'Vertragsende innerhalb der n&auml;chsten 2 Monate',
                margin: '10 0 10 0',
                store: storeVertragsdaten,
                columns: [
                      {
                          xtype: 'datecolumn',
                          dataIndex: 'end',
                          text: 'Vertragsende',
                          format: 'd.m.y',
                          width: 80,
                      },                          
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'hiwi',
                        text: 'Name',
                        flex: 1,
//                        renderer: function(val, meta, record) {
//                            return record.data.vorname + " " + record.data.name;
//                      }

                    },

//                    {
//                        xtype: 'numbercolumn',
//                        dataIndex: 'beginn',
//                        text: 'Vertragsbeginn',
//                    	  format: 'd.m.y',
//                    },
                    {
                        xtype: 'numbercolumn',
                        dataIndex: 'remainingHours',
                        text: 'Offene Stunden',                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'remainingTasks',
                        text: 'Offene Aufgaben',
                    },                    
//                    {
//                        xtype: 'gridcolumn',
//                        text: 'Tarif',
//                        dataIndex: 'rate',
//                    }
                ],
                viewConfig: {

                }
            },
            {
                xtype: 'form',
                height: 87,
                itemId: 'infoForm',
                padding: '',
                layout: {
                    columns: 2,
                    type: 'table'
                },
                bodyPadding: 10,
                items: [
                    {
                        xtype: 'displayfield',
                        width: 250,
                        name: 'budget',
                        value: 'Display Field',
                        fieldLabel: 'Budget',
                        anchor: '100%'
                    },
                    {
                        xtype: 'displayfield',
                        name: 'aktiveHiWis',
                        value: 'Display Field',
                        fieldLabel: 'Aktive HiWis',
                        anchor: '100%'
                    },
                    {
                        xtype: 'displayfield',
                        name: 'vorgesetzter',
                        value: 'Display Field',
                        fieldLabel: 'Vorgesetzter'
                    },
                    {
                        xtype: 'displayfield',
                        name: 'aktiveAufgaben',
                        value: 'Display Field',
                        fieldLabel: 'Aktive Aufgaben'
                    },
                    {
                        xtype: 'displayfield',
                        name: 'fachgruppe',
                        value: 'Display Field',
                        fieldLabel: 'Fachgruppe'
                    }
                ]
            },
            {
                xtype: 'gridpanel',
                itemId: 'aufgabenDeadlineGrid',
                title: 'Aufgaben Deadlines',
                margin: '10 0 0 0',
                store: storeAufgaben,
                columns: [
                    {
                        xtype: 'datecolumn',
                        dataIndex: 'deadline',
                        width: 65,
                        text: 'Deadline',
                        format: 'd.m.y',
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'title',
                        text: 'Aufgabe',
                        flex: 1
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'hiwi',
                        text: 'HiWi',
                        width: 170,
                    },
                    {
                        xtype: 'datecolumn',
                        dataIndex: 'assignedAt',
                        text: 'Zugewiesen am',
                        format: 'd.m.y',
                    },   
                    {
                        xtype: 'numbercolumn',
                        dataIndex: 'priority',
                        text: 'Priorität',
                        format: '0',
                        width: 60
//                        allowNegative: false,                    	
                    }                    
                ],
                viewConfig: {

                }
            }
        ];
        me.callParent(arguments);
    }
});